'use client'

// ─────────────────────────────────────────────────────────────────────────────
// Zillit Global Rates Bible — AI Assistant Panel
// Claude-powered chat panel. Loaded with all rate data via the system prompt.
// The AI_SYSTEM_PROMPT is imported from a separate file generated by
// data-extract.js — it contains the full compressed BIBLE as context.
// ─────────────────────────────────────────────────────────────────────────────

import { useRef, useEffect, useState } from 'react'
import { AiMessage } from './types'
import { useRatesStore, useAiOpen, useAiHistory } from './useRatesStore'

// ── QUICK PROMPTS ─────────────────────────────────────────────────────────────

const QUICK_PROMPTS = [
  'UK Camera holiday pay?',
  'SAG meal penalty rates?',
  'BECTU turnaround rules?',
  'DGA UPM weekly rate?',
  'Germany 12hr absolute max?',
  'Canada BCCFU OT structure?',
  'France ASSEDIC %?',
  'Australia super rate?',
  'MMP 6th day rule?',
  'TV Drama ACH explained?',
]

// ── AI SYSTEM PROMPT ──────────────────────────────────────────────────────────
// This should be imported from a generated file produced by data-extract.js.
// The generator script outputs all rate data, rules, and working provisions
// in a compressed format optimised for the LLM context window.
//
// import { AI_SYSTEM_PROMPT } from '@/data/aiSystemPrompt'
//
// For development, import from the HTML directly or use a placeholder:

const AI_SYSTEM_PROMPT = `You are a specialist production accounting and payroll assistant for the Zillit Global Production Rates Bible. You have detailed knowledge of:

- All 19 UK BECTU branches (Camera, ADs, Art Dept, Lighting, SFX, Costume, HMU, Construction, Set Crafts, Props, Locations, Post Production Film, Post Production TV, Post-Sound, LPD Production, FAA Background Artistes, BBC Scotland, PACT/Equity, Animation & VFX)
- The complete PACT/BECTU Major Motion Picture Agreement (MMP) and TV Drama Agreement 2023 including all working rules, overtime rates, meal penalties, turnaround provisions
- USA (SAG-AFTRA, DGA, IATSE Local 600/695/44, WGA), Canada (BCCFU, IATSE 873 Ontario, DGC), Germany (Ver.di TV FFS), France (CCN IDCC 3097), Ireland (SIPTU/SPI), Australia (MPPA), and 25+ additional territories
- All applicable production incentives and tax credits by territory

When answering:
- Be precise with figures — always quote the exact rate, not approximations
- For UK rates, always clarify which branch and budget tier applies
- Flag holiday pay treatment (included/excluded/separate) whenever quoting UK rates
- For OT calculations, show the formula clearly
- If a rate is Ind. Neg. or Own Negotiation, say so explicitly
- Keep answers concise and deal-memo ready`

// ── COMPONENT ─────────────────────────────────────────────────────────────────

export function AIAssistantPanel() {
  const aiOpen    = useAiOpen()
  const aiHistory = useAiHistory()
  const { closeAI, addAiMessage, trimAiHistory } = useRatesStore()

  const [input, setInput]     = useState('')
  const [loading, setLoading] = useState(false)
  const msgsRef = useRef<HTMLDivElement>(null)

  // Scroll to bottom on new messages
  useEffect(() => {
    if (msgsRef.current) {
      msgsRef.current.scrollTop = msgsRef.current.scrollHeight
    }
  }, [aiHistory, loading])

  const send = async (q: string) => {
    if (!q.trim() || loading) return
    setInput('')

    const userMsg: AiMessage = { role: 'user', content: q }
    addAiMessage(userMsg)
    trimAiHistory()
    setLoading(true)

    try {
      const res = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model: 'claude-sonnet-4-20250514',
          max_tokens: 900,
          system: AI_SYSTEM_PROMPT,
          messages: [...aiHistory, userMsg],
        }),
      })
      const data = await res.json()
      const text = data.content?.[0]?.text ?? 'Sorry, I could not generate a response.'
      addAiMessage({ role: 'assistant', content: text })
    } catch {
      addAiMessage({ role: 'assistant', content: 'Network error. Please try again.' })
    } finally {
      setLoading(false)
    }
  }

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      send(input)
    }
  }

  return (
    <div className={[
      'flex-shrink-0 flex flex-col bg-bg-s border-l border-border overflow-hidden',
      'transition-all duration-200',
      aiOpen ? 'w-72' : 'w-0 border-none',
    ].join(' ')}>

      {/* ── Header ──────────────────────────────────────────────────────── */}
      <div className="flex items-center gap-2 px-3 py-2.5 border-b border-border flex-shrink-0">
        <div className="w-6 h-6 rounded-md bg-gold-glow border border-gold/20
                        flex items-center justify-center text-sm flex-shrink-0">
          ✦
        </div>
        <div className="flex-1 min-w-0">
          <div className="font-syne font-black text-sm">Rates Assistant</div>
          <div className="text-2xs text-text-3">34 territories · 57 confirmed</div>
        </div>
        <button
          onClick={closeAI}
          className="text-text-3 hover:text-text-1 transition-colors text-sm px-1"
        >
          ✕
        </button>
      </div>

      {/* ── Messages ────────────────────────────────────────────────────── */}
      <div ref={msgsRef} className="flex-1 overflow-y-auto p-2.5 space-y-2">
        {/* Welcome message */}
        {aiHistory.length === 0 && (
          <AssistantMessage>
            I have confirmed rate data for <strong>UK (19 BECTU branches with all budget tiers), USA (SAG-AFTRA, DGA, IATSE, WGA), Canada (BCCFU, IATSE 873 Ontario)</strong>, and framework data for 30+ territories. Ask me anything — deal memos, OT calculations, meal penalties, turnaround rules.
          </AssistantMessage>
        )}

        {/* Conversation */}
        {aiHistory.map((msg, i) =>
          msg.role === 'user'
            ? <UserMessage key={i}>{msg.content}</UserMessage>
            : <AssistantMessage key={i}>{msg.content}</AssistantMessage>
        )}

        {/* Typing indicator */}
        {loading && (
          <div className="flex items-start gap-1.5">
            <div className="w-5 h-5 rounded-full bg-gold-glow border border-gold/20
                            flex items-center justify-center text-2xs flex-shrink-0 mt-0.5">
              ✦
            </div>
            <div className="bg-bg-e border border-border rounded-md px-3 py-2">
              <div className="flex gap-1">
                {[0, 1, 2].map(i => (
                  <div key={i}
                    className="w-1 h-1 rounded-full bg-text-3 animate-typing-dot"
                    style={{ animationDelay: `${i * 0.2}s` }}
                  />
                ))}
              </div>
            </div>
          </div>
        )}
      </div>

      {/* ── Input ───────────────────────────────────────────────────────── */}
      <div className="px-2.5 py-2 border-t border-border flex-shrink-0">
        {/* Quick prompts */}
        <div className="mb-1.5">
          <p className="font-syne font-bold text-2xs uppercase tracking-wide text-text-3 mb-1">
            Try asking
          </p>
          <div className="flex gap-1 flex-wrap">
            {QUICK_PROMPTS.slice(0, 6).map(q => (
              <button
                key={q}
                onClick={() => send(q)}
                disabled={loading}
                className="bg-bg-e border border-border rounded-full px-2 py-0.5
                           font-syne font-bold text-2xs text-text-3
                           hover:border-gold hover:text-gold transition-all disabled:opacity-50"
              >
                {q}
              </button>
            ))}
          </div>
        </div>

        {/* Text input */}
        <div className="flex gap-1.5">
          <textarea
            value={input}
            onChange={e => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="SAG meal penalty? BECTU turnaround?"
            rows={1}
            className="flex-1 bg-bg-e border border-border-mid rounded-sm px-2 py-1.5
                       text-sm text-text-1 placeholder:text-text-3 resize-none
                       focus:outline-none focus:border-gold transition-colors"
          />
          <button
            onClick={() => send(input)}
            disabled={loading || !input.trim()}
            className="bg-gold text-bg font-bold rounded-sm px-2.5 py-1.5 text-base
                       hover:opacity-85 transition-opacity disabled:opacity-40"
          >
            ↑
          </button>
        </div>
      </div>
    </div>
  )
}

// ── MESSAGE BUBBLES ───────────────────────────────────────────────────────────

function UserMessage({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex justify-end">
      <div className="bg-gold-glow border border-gold/15 rounded-md rounded-tr-sm
                      px-2.5 py-1.5 max-w-[90%] text-sm leading-relaxed">
        {children}
      </div>
    </div>
  )
}

function AssistantMessage({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex items-start gap-1.5">
      <div className="w-5 h-5 rounded-full bg-gold-glow border border-gold/20
                      flex items-center justify-center text-2xs flex-shrink-0 mt-0.5">
        ✦
      </div>
      <div className="bg-bg-e border border-border rounded-md rounded-tl-sm px-2.5 py-1.5 text-sm leading-relaxed">
        {formatAiText(String(children))}
      </div>
    </div>
  )
}

/** Converts **bold** markdown and newlines to JSX */
function formatAiText(text: string) {
  return text.split('\n').map((line, i) => (
    <span key={i}>
      {line.split(/(\*\*.*?\*\*)/).map((part, j) =>
        part.startsWith('**') && part.endsWith('**')
          ? <strong key={j} className="font-bold text-text-1">{part.slice(2, -2)}</strong>
          : part
      )}
      {i < text.split('\n').length - 1 && <br />}
    </span>
  ))
}
