// Budget tiers for UK film and TV production
// Source: Pact/BECTU agreements, Pact/Equity Cinema Films Agreement
export const budgetTiers = [
  // ─── FILM TIERS (BECTU / Equity) ───────────────
  {
    name: 'MMP (£30m+)',
    code: 'FILM_MMP',
    unionCode: null, // Applies to all unions
    productionType: 'feature_film',
    minBudget: 30000000,
    maxBudget: null,
    description: 'Major Motion Picture Agreement — productions with budgets £30m and above',
    sortOrder: 1,
  },
  {
    name: 'Film £15m-£30m',
    code: 'FILM_15_30',
    unionCode: null,
    productionType: 'feature_film',
    minBudget: 15000000,
    maxBudget: 30000000,
    description: 'High budget feature films £15m to £30m',
    sortOrder: 2,
  },
  {
    name: 'Film £5m-£15m',
    code: 'FILM_5_15',
    unionCode: null,
    productionType: 'feature_film',
    minBudget: 5000000,
    maxBudget: 15000000,
    description: 'Mid budget feature films £5m to £15m',
    sortOrder: 3,
  },
  {
    name: 'Film £3m-£5m',
    code: 'FILM_3_5',
    unionCode: null,
    productionType: 'feature_film',
    minBudget: 3000000,
    maxBudget: 5000000,
    description: 'Lower budget feature films £3m to £5m. Equity +280% uplift tier.',
    sortOrder: 4,
  },
  {
    name: 'Film £1m-£3m',
    code: 'FILM_1_3',
    unionCode: null,
    productionType: 'feature_film',
    minBudget: 1000000,
    maxBudget: 3000000,
    description: 'Low budget features £1m to £3m. Equity +75% uplift tier.',
    sortOrder: 5,
  },
  {
    name: 'Film Under £1m',
    code: 'FILM_U1',
    unionCode: null,
    productionType: 'feature_film',
    minBudget: 0,
    maxBudget: 1000000,
    description: 'Ultra low budget features under £1m. Equity +50% uplift tier.',
    sortOrder: 6,
  },

  // ─── TV DRAMA TIERS (Pact/BECTU TV Drama Agreement) ──
  {
    name: 'TV Band 4 (£8m+/hr)',
    code: 'TV_BAND4',
    unionCode: null,
    productionType: 'tv_drama',
    minBudget: 8000000,
    maxBudget: null,
    description: 'TV Drama Band 4 — above £8,000,000 per broadcast hour',
    sortOrder: 7,
  },
  {
    name: 'TV Band 3 (£3m-£8m/hr)',
    code: 'TV_BAND3',
    unionCode: null,
    productionType: 'tv_drama',
    minBudget: 3000000,
    maxBudget: 8000000,
    description: 'TV Drama Band 3 — £3,000,000 to £8,000,000 per broadcast hour',
    sortOrder: 8,
  },
  {
    name: 'TV Band 2 (£1.25m-£3m/hr)',
    code: 'TV_BAND2',
    unionCode: null,
    productionType: 'tv_drama',
    minBudget: 1250000,
    maxBudget: 3000000,
    description: 'TV Drama Band 2 — £1,250,000 to £3,000,000 per broadcast hour',
    sortOrder: 9,
  },
  {
    name: 'TV Band 1 (Under £1.25m/hr)',
    code: 'TV_BAND1',
    unionCode: null,
    productionType: 'tv_drama',
    minBudget: 0,
    maxBudget: 1250000,
    description: 'TV Drama Band 1 — up to £1,250,000 per broadcast hour',
    sortOrder: 10,
  },

  // ─── COMMERCIAL / OTHER ────────────────────────
  {
    name: 'Commercial',
    code: 'COMMERCIAL',
    unionCode: null,
    productionType: 'commercial',
    minBudget: 0,
    maxBudget: null,
    description: 'TV commercials, corporate films, pop promos',
    sortOrder: 11,
  },
  {
    name: 'Short Film',
    code: 'SHORT',
    unionCode: null,
    productionType: 'short_film',
    minBudget: 0,
    maxBudget: null,
    description: 'Short films (typically under 40 minutes)',
    sortOrder: 12,
  },
  {
    name: 'Documentary',
    code: 'DOCUMENTARY',
    unionCode: null,
    productionType: 'documentary',
    minBudget: 0,
    maxBudget: null,
    description: 'Documentary productions',
    sortOrder: 13,
  },
];
