/**
 * Territory Rules: One entry per union agreement.
 * Extracted from Kate's TERRITORY_RULES dataset (production accounting standard).
 * Each contains 40+ fields covering OT, meals, rest, fringes, allowances.
 */
export const territoryRules = [
  // ═══════════════════════════════════════════════════════════════════
  // UK AGREEMENTS
  // ═══════════════════════════════════════════════════════════════════
  {
    territoryCode: 'UK', unionKey: 'PACT-BECTU', badge: 'BECTU MMP',
    effectiveFrom: new Date('2024-01-01'),
    basicHrs: 11, basicDescription: '11 hrs (SWD: 11+1hr lunch)', hrBasis: 'Weekly ÷ 5 ÷ 11',
    // OT
    ot1Multiplier: 1.5, ot1Trigger: 'Hours 12-13 (non-camera)', ot1Description: '×1.5 after 11hrs',
    ot2Multiplier: 2.0, ot2Trigger: 'Hours 13+ (non-camera)', ot2Description: '×2.0 after 13hrs',
    goldenTimeMultiplier: null, goldenTimeAfterHours: null, goldenTimeDescription: null,
    otRateCap: 81.82, otRateCapDescription: 'Max OT rate £81.82/hr (Camera & non-camera)',
    // Day premiums
    sixthDayMultiplier: 1.5, sixthDayDescription: '×1.5 all hours (min 6hrs non-shoot, 8hrs shoot)',
    seventhDayMultiplier: 2.0, seventhDayDescription: '×2.0 all hours (same minimums)',
    // Holiday/vacation
    holidayPayPct: 0.1207, holidayPayDescription: '12.07% on all labour earnings (basic + OT)',
    hpMode: 'excl', vacationPct: null, vacationDescription: null,
    // Night
    nightPremiumType: 'flat', nightPremiumValue: 20, nightStartTime: '20:00', nightEndTime: '06:00',
    nightDescription: '£20 flat per night worked (MMP agreement)',
    // Meals
    mealIntervalHrs: 6, mealDurationMins: 30, mealPaidStatus: 'unpaid',
    mealSubsequentInterval: 6, mealGraceMinutes: 0,
    mealPenaltyAmounts: [35], mealPenaltyDescription: '£35 per breach (Camera OT rate in 15-min increments)',
    mealPenalty2Description: '£35 each additional 6-hr period', frenchHoursAllowed: false,
    // Rest
    turnaroundMinHrs: 11, turnaroundDescription: '11 hrs wrap-to-call (endeavour)',
    turnaroundPenaltyType: 'hourly_rate', turnaroundPenaltyDescription: '1.5T in 30-min increments per invaded half-hour',
    weeklyRestMinHrs: 24, dayBreakDescription: '20 min per 6 hrs worked',
    // Fringes
    rfHolidayPayPct: 0.1207, rfHolidayPayDescription: '12.07% on basic + OT, posts to 2302',
    rfNicPct: 0.138, rfNicThreshold: 967, rfNicDescription: '13.8% above £967/wk, posts to 2399',
    rfPensionPct: 0.03, rfPensionDescription: '3% min auto-enrol',
    rfHwPerHour: null, rfHwDescription: null,
    rfEmployerTotalEstimate: '~26%', rfWorkersCompPct: null,
    // Allowances
    rfKitDefault: 500, rfMileageRate: '45p/mile (first 10,000)', rfPerDiemDefault: 35,
    rfPerDiemMandatory: false,
    // Working day types
    workingDayTypes: ['SWD', 'CWD', 'SCWD'], achApplicable: false,
    // Tax credit
    rfTaxCreditScheme: 'HETVC',
    // Special
    specialProvisions: [
      'Camera OT at 2T (double time), NOT 1.5T — specific to Camera branch',
      'Pre-dawn call (before 05:00) attracts Camera OT rate (2T)',
      'Grace periods ABOLISHED in 2023 agreement — OT from minute one',
      'Saturday/Sunday NOT automatically premium — only 6th/7th consecutive day',
      'Travel days on 6th/7th do NOT count as consecutive working days',
    ],
  },

  {
    territoryCode: 'UK', unionKey: 'PACT-BECTU-TV', badge: 'BECTU TV Drama',
    effectiveFrom: new Date('2023-01-01'),
    basicHrs: 10, basicDescription: '10 hrs (ACH adds 1hr for eligible depts)', hrBasis: 'Daily ÷ 10',
    ot1Multiplier: 1.5, ot1Trigger: 'After standard day', ot1Description: '×1.5 (min cap £35/hr, max cap £70/hr)',
    ot2Multiplier: 2.0, ot2Trigger: 'After 23:00', ot2Description: '×2.0 enhanced OT after 11pm',
    goldenTimeMultiplier: null, goldenTimeAfterHours: null, goldenTimeDescription: null,
    otRateCap: 70, otRateCapDescription: 'Max OT rate £70/hr (or crew hourly rate if greater)',
    sixthDayMultiplier: 1.5, sixthDayDescription: '6th day shoot: all 10hrs at 1.5T',
    seventhDayMultiplier: 2.0, seventhDayDescription: '7th day: 2T',
    holidayPayPct: 0.1207, holidayPayDescription: '12.07%', hpMode: 'excl',
    vacationPct: null, vacationDescription: null,
    nightPremiumType: 'tiered', nightPremiumValue: null,
    nightStartTime: '23:00', nightEndTime: '06:00', nightDescription: '2T after 23:00',
    mealIntervalHrs: 6, mealDurationMins: 30, mealPaidStatus: 'unpaid',
    mealSubsequentInterval: 6, mealGraceMinutes: 0,
    mealPenaltyAmounts: [35], mealPenaltyDescription: 'OT rate (1.5T) in 15-min increments',
    frenchHoursAllowed: false,
    turnaroundMinHrs: 11, turnaroundDescription: '11 hrs',
    turnaroundPenaltyType: 'hourly_rate', turnaroundPenaltyDescription: '0.5T per 15-min increment (disputed)',
    weeklyRestMinHrs: 24, dayBreakDescription: '20 min per 6 hrs',
    rfHolidayPayPct: 0.1207, rfHolidayPayDescription: '12.07%',
    rfNicPct: 0.138, rfNicThreshold: 967, rfNicDescription: '13.8% above £967/wk',
    rfPensionPct: 0.03, rfPensionDescription: '3%',
    rfHwPerHour: null, rfHwDescription: null,
    rfEmployerTotalEstimate: '~26%', rfWorkersCompPct: null,
    rfKitDefault: 500, rfMileageRate: '45p/mile', rfPerDiemDefault: 35, rfPerDiemMandatory: false,
    workingDayTypes: ['SWD', 'CWD', 'SCWD'], achApplicable: true,
    rfTaxCreditScheme: 'HETVC',
    specialProvisions: [
      'ACH (Additional Contracted Hour) applies to ADs, Costume, HMU, Locations, Production — 1 extra hour at 1T',
      'Early call premium: 0.5T (half hourly rate) — NOT full OT',
      'Broken turnaround: BECTU disputes 0.5T rate as unilateral change — arbitration ruled for BECTU on principle',
    ],
  },

  {
    territoryCode: 'UK', unionKey: 'EQUITY', badge: 'Equity Cinema',
    effectiveFrom: new Date('2024-01-01'),
    basicHrs: 10, basicDescription: '10 hrs', hrBasis: 'Daily ÷ 10',
    ot1Multiplier: 1.5, ot1Trigger: 'After 10hrs', ot1Description: '×1.5 after standard day',
    ot2Multiplier: 2.0, ot2Trigger: 'After 12hrs', ot2Description: '×2.0',
    goldenTimeMultiplier: null, goldenTimeAfterHours: null, goldenTimeDescription: null,
    otRateCap: 94, otRateCapDescription: 'Max £94/hr',
    sixthDayMultiplier: 1.5, sixthDayDescription: '×1.5',
    seventhDayMultiplier: 2.0, seventhDayDescription: '×2.0',
    holidayPayPct: 0.1207, holidayPayDescription: '12.07%', hpMode: 'excl',
    vacationPct: null, vacationDescription: null,
    nightPremiumType: 'percentage', nightPremiumValue: 50, nightStartTime: '20:00', nightEndTime: '06:00',
    nightDescription: '+50% of daily fee after 20:00',
    mealIntervalHrs: 6, mealDurationMins: 30, mealPaidStatus: 'unpaid',
    mealSubsequentInterval: 6, mealGraceMinutes: 0,
    mealPenaltyAmounts: [35], mealPenaltyDescription: '£35 per breach',
    frenchHoursAllowed: false,
    turnaroundMinHrs: 12, turnaroundDescription: '12 hrs (reducible to 11 by agreement)',
    turnaroundPenaltyType: 'hourly_rate', turnaroundPenaltyDescription: 'Penalty rate for invaded hours',
    weeklyRestMinHrs: 24, dayBreakDescription: '20 min per 6 hrs',
    rfHolidayPayPct: 0.1207, rfNicPct: 0.138, rfNicThreshold: 967,
    rfPensionPct: 0.03, rfHwPerHour: null, rfEmployerTotalEstimate: '~26%',
    rfKitDefault: 0, rfMileageRate: '45p/mile', rfPerDiemDefault: 35, rfPerDiemMandatory: false,
    workingDayTypes: ['SWD'], achApplicable: false, rfTaxCreditScheme: 'HETVC',
    specialProvisions: ['Performers have 12hr turnaround (not 9hr)', 'Day player vs weekly vs 3-day rates'],
  },

  // ═══════════════════════════════════════════════════════════════════
  // US AGREEMENTS
  // ═══════════════════════════════════════════════════════════════════
  {
    territoryCode: 'US', unionKey: 'IATSE-BASIC', badge: 'IATSE Basic',
    effectiveFrom: new Date('2024-07-01'),
    basicHrs: 8, basicDescription: '8 hrs', hrBasis: 'Rate ÷ 8',
    ot1Multiplier: 1.5, ot1Trigger: 'Hours 9-12', ot1Description: '×1.5 after 8hrs',
    ot2Multiplier: 2.0, ot2Trigger: 'Hours 13-14', ot2Description: '×2.0 after 12hrs',
    goldenTimeMultiplier: 2.0, goldenTimeAfterHours: 14, goldenTimeDescription: 'Flat ×2.0 from hour 14 onward (golden time)',
    otRateCap: null, otRateCapDescription: null,
    sixthDayMultiplier: 1.5, sixthDayDescription: '×1.5 first 8hrs, then ×2.0',
    seventhDayMultiplier: 2.0, seventhDayDescription: '×2.0 all hours',
    holidayPayPct: null, holidayPayDescription: null, hpMode: 'na',
    vacationPct: 0.06719, vacationDescription: '6.719% on gross wages paid to H&W',
    nightPremiumType: 'percentage', nightPremiumValue: 10, nightStartTime: '00:00', nightEndTime: '06:00',
    nightDescription: '+10% for hours worked 0000-0600',
    mealIntervalHrs: 6, mealDurationMins: 30, mealPaidStatus: 'non-deductible',
    mealSubsequentInterval: 6, mealGraceMinutes: 0,
    mealPenaltyAmounts: [75, 25], mealPenaltyDescription: '$75 first 30min, $25 per subsequent 30min',
    mealPenalty2Description: '$25 per 30-min interval after first', frenchHoursAllowed: true,
    turnaroundMinHrs: 10, turnaroundDescription: '10hrs studio / 9hrs distant location',
    turnaroundPenaltyType: 'continuous_day', turnaroundPenaltyDescription: 'Forced call 10hr minimum at straight time',
    weeklyRestMinHrs: 24, dayBreakDescription: 'Per applicable state law',
    rfHolidayPayPct: null, rfHolidayPayDescription: null,
    rfNicPct: 0.0765, rfNicThreshold: null, rfNicDescription: '7.65% FICA (6.2% SS + 1.45% Medicare) + FUTA/SUTA ~3.5%',
    rfPensionPct: 0.075, rfPensionDescription: '7.5% of gross to pension fund',
    rfHwPerHour: 26.76, rfHwDescription: '$26.76/hr (Local 600 Camera); varies by local ($26-$34)',
    rfEmployerTotalEstimate: '~40-45%', rfWorkersCompPct: 0.035,
    rfKitDefault: 100, rfMileageRate: '67¢/mile (IRS rate)', rfPerDiemDefault: 150,
    rfPerDiemMandatory: true,
    workingDayTypes: [], achApplicable: false, rfTaxCreditScheme: 'US_STATE',
    specialProvisions: [
      'Non-deductible meals — clock keeps running during meal breaks',
      'Golden time from hour 14 at flat ×2.0 (not escalating)',
      'Studio Zone: 30-mile radius from La Brea & Beverly Blvd',
      'H&W qualifying hours tracked — pension vesting period applies',
      'Forced call after turnaround violation: 10hr minimum at straight time',
      'AI protections from 2023 strike provisions (IATSE New Media)',
    ],
  },

  {
    territoryCode: 'US', unionKey: 'DGA', badge: 'DGA Basic',
    effectiveFrom: new Date('2025-07-01'),
    basicHrs: 12, basicDescription: 'Weekly guarantee (no daily basic)', hrBasis: 'Weekly guarantee structure',
    ot1Multiplier: 1.5, ot1Trigger: 'Extended day (varies by role)', ot1Description: '150% pro-rata daily for 6th day in-town',
    ot2Multiplier: 2.0, ot2Trigger: '7th day or holiday', ot2Description: '200% OR weekly + $4,413',
    goldenTimeMultiplier: null, goldenTimeAfterHours: null, goldenTimeDescription: 'Extended day (>15-16hrs) = extra days pay',
    otRateCap: null, otRateCapDescription: null,
    sixthDayMultiplier: 1.5, sixthDayDescription: '150% pro-rata daily (in-town)',
    seventhDayMultiplier: 2.0, seventhDayDescription: '200% OR weekly rate + $4,413',
    holidayPayPct: null, holidayPayDescription: null, hpMode: 'na',
    vacationPct: 0.08583, vacationDescription: '8.583% vacation/holiday',
    nightPremiumType: null, nightPremiumValue: null, nightStartTime: null, nightEndTime: null,
    nightDescription: null,
    mealIntervalHrs: 6, mealDurationMins: 30, mealPaidStatus: 'non-deductible',
    mealSubsequentInterval: 6, mealGraceMinutes: 0,
    mealPenaltyAmounts: [75], mealPenaltyDescription: '$75 per violation',
    frenchHoursAllowed: false,
    turnaroundMinHrs: 9, turnaroundDescription: '9 hrs free night',
    turnaroundPenaltyType: 'flat_penalty', turnaroundPenaltyDescription: 'Additional compensation for invaded hours',
    weeklyRestMinHrs: 24, dayBreakDescription: 'Per DGA agreement',
    rfHolidayPayPct: null,
    rfNicPct: 0.0765, rfNicThreshold: null, rfNicDescription: '7.65% FICA',
    rfPensionPct: 0.06, rfPensionDescription: '6% pension (8.75% pension + 11.25% health = employer, 2.5% employee)',
    rfHwPerHour: null, rfHwDescription: 'Included in pension/health contribution',
    rfEmployerTotalEstimate: '~35-40%', rfWorkersCompPct: 0.035,
    rfKitDefault: 0, rfMileageRate: '67¢/mile', rfPerDiemDefault: 150,
    rfPerDiemMandatory: true,
    workingDayTypes: [], achApplicable: false, rfTaxCreditScheme: 'US_STATE',
    specialProvisions: [
      'Weekly guarantee structure — NOT daily basic',
      'Deal memo must be filed with DGA office within 15 days',
      'UPM vs AD have separate rate scales',
      'On-call provisions for UPMs',
      'Pension vesting period applies',
      '+0.5% parental leave contribution',
    ],
  },

  {
    territoryCode: 'US', unionKey: 'SAG-THEATRICAL', badge: 'SAG Theatrical',
    effectiveFrom: new Date('2025-07-01'),
    basicHrs: 8, basicDescription: '8 hrs', hrBasis: 'Daily ÷ 8',
    ot1Multiplier: 1.5, ot1Trigger: 'Hours 9-10', ot1Description: '×1.5',
    ot2Multiplier: 2.0, ot2Trigger: 'Hours 11-15', ot2Description: '×2.0',
    goldenTimeMultiplier: null, goldenTimeAfterHours: 16,
    goldenTimeDescription: "Hour 16+: Day's pay per hour worked",
    otRateCap: null, otRateCapDescription: null,
    sixthDayMultiplier: 1.5, sixthDayDescription: '×1.5',
    seventhDayMultiplier: 2.0, seventhDayDescription: '×2.0',
    holidayPayPct: null, holidayPayDescription: null, hpMode: 'na',
    vacationPct: null, vacationDescription: null,
    nightPremiumType: null, nightPremiumValue: null, nightStartTime: null, nightEndTime: null,
    nightDescription: null,
    mealIntervalHrs: 6, mealDurationMins: 30, mealPaidStatus: 'non-deductible',
    mealSubsequentInterval: 6, mealGraceMinutes: 0,
    mealPenaltyAmounts: [25, 35, 50], mealPenaltyDescription: '$25 first 30min, $35 second 30min, $50 subsequent',
    frenchHoursAllowed: false,
    turnaroundMinHrs: 12, turnaroundDescription: '12hrs (studio), 10hrs (location)',
    turnaroundPenaltyType: 'flat_penalty', turnaroundPenaltyDescription: "Forced call: 1 day's pay or $900",
    weeklyRestMinHrs: 24, dayBreakDescription: 'Per SAG agreement',
    rfHolidayPayPct: null,
    rfNicPct: 0.0765, rfNicThreshold: null, rfNicDescription: '7.65% FICA',
    rfPensionPct: 0.185, rfPensionDescription: '18.5% P&H on ALL earnings including overscale (major cost)',
    rfHwPerHour: null, rfHwDescription: 'Included in 18.5% P&H',
    rfEmployerTotalEstimate: '~30-35%', rfWorkersCompPct: 0.035,
    rfKitDefault: 0, rfMileageRate: '67¢/mile', rfPerDiemDefault: 90,
    rfPerDiemMandatory: true,
    workingDayTypes: [], achApplicable: false, rfTaxCreditScheme: 'US_STATE',
    specialProvisions: [
      'P&H at 18.5% on ALL earnings including overscale — major cost item',
      '12-hour performer turnaround (not 9hr like IATSE)',
      'Day player vs weekly vs 3-day contract types',
      'Stunt adjustment factors apply',
      'Background performers under separate agreement',
      'Taft-Hartley for non-members (30 days to join)',
    ],
  },

  {
    territoryCode: 'US', unionKey: 'WGA-WEST', badge: 'WGA West',
    effectiveFrom: new Date('2025-05-01'),
    basicHrs: 0, basicDescription: 'Deliverables-based (no daily/hourly)', hrBasis: 'Per-script / step deal',
    ot1Multiplier: null, ot1Trigger: null, ot1Description: 'N/A — writers have no OT',
    ot2Multiplier: null, ot2Trigger: null, ot2Description: null,
    goldenTimeMultiplier: null, goldenTimeAfterHours: null, goldenTimeDescription: null,
    otRateCap: null, otRateCapDescription: null,
    sixthDayMultiplier: null, sixthDayDescription: null,
    seventhDayMultiplier: null, seventhDayDescription: null,
    holidayPayPct: null, holidayPayDescription: null, hpMode: 'na',
    vacationPct: null, vacationDescription: null,
    nightPremiumType: null, nightPremiumValue: null, nightStartTime: null, nightEndTime: null,
    nightDescription: null,
    mealIntervalHrs: null, mealDurationMins: null, mealPaidStatus: null,
    mealSubsequentInterval: null, mealGraceMinutes: null,
    mealPenaltyAmounts: [], mealPenaltyDescription: 'N/A for writers',
    frenchHoursAllowed: false,
    turnaroundMinHrs: null, turnaroundDescription: 'N/A for writers',
    turnaroundPenaltyType: null, turnaroundPenaltyDescription: null,
    weeklyRestMinHrs: null, dayBreakDescription: null,
    rfHolidayPayPct: null,
    rfNicPct: 0.0765, rfNicThreshold: null, rfNicDescription: '7.65% FICA',
    rfPensionPct: 0.21, rfPensionDescription: '21% P&H — HIGHEST in the industry',
    rfHwPerHour: null, rfHwDescription: 'Included in 21% P&H',
    rfEmployerTotalEstimate: '~25-30%', rfWorkersCompPct: null,
    rfKitDefault: 0, rfMileageRate: '67¢/mile', rfPerDiemDefault: 0, rfPerDiemMandatory: false,
    workingDayTypes: [], achApplicable: false, rfTaxCreditScheme: 'US_STATE',
    specialProvisions: [
      'Step deal structure: story, treatment, first draft, revisions, optional polish',
      'No OT, meal, or rest rules for writers',
      '21% P&H — highest rate of any guild',
      '2023 strike provisions on AI use, room sizes, streaming residuals',
      'WGA West covers LA-based writers, WGA East covers NY-based',
    ],
  },

  {
    territoryCode: 'US', unionKey: 'TEAMSTERS-399', badge: 'Teamsters 399',
    effectiveFrom: new Date('2024-07-01'),
    basicHrs: 8, basicDescription: '8 hrs', hrBasis: 'Rate ÷ 8',
    ot1Multiplier: 1.5, ot1Trigger: 'After 8hrs', ot1Description: '×1.5',
    ot2Multiplier: 2.0, ot2Trigger: 'After 12hrs', ot2Description: '×2.0',
    goldenTimeMultiplier: 2.0, goldenTimeAfterHours: 14, goldenTimeDescription: 'Same as IATSE',
    otRateCap: null, otRateCapDescription: null,
    sixthDayMultiplier: 1.5, sixthDayDescription: '×1.5',
    seventhDayMultiplier: 2.0, seventhDayDescription: '×2.0',
    holidayPayPct: null, holidayPayDescription: null, hpMode: 'na',
    vacationPct: 0.09, vacationDescription: '9% vacation',
    nightPremiumType: 'percentage', nightPremiumValue: 15, nightStartTime: '00:00', nightEndTime: '06:00',
    nightDescription: '+15% night differential',
    mealIntervalHrs: 6, mealDurationMins: 30, mealPaidStatus: 'non-deductible',
    mealSubsequentInterval: 6, mealGraceMinutes: 0,
    mealPenaltyAmounts: [35], mealPenaltyDescription: '$35 per violation',
    frenchHoursAllowed: false,
    turnaroundMinHrs: 10, turnaroundDescription: '10 hrs',
    turnaroundPenaltyType: 'continuous_day',
    turnaroundPenaltyDescription: 'Forced call at straight time',
    weeklyRestMinHrs: 24, dayBreakDescription: 'Per DOT regulations',
    rfHolidayPayPct: null,
    rfNicPct: 0.0765, rfNicThreshold: null, rfNicDescription: '7.65% FICA',
    rfPensionPct: 0.075, rfPensionDescription: '7.5% pension',
    rfHwPerHour: 30, rfHwDescription: '~$28-$34/hr H&W',
    rfEmployerTotalEstimate: '~40%', rfWorkersCompPct: 0.035,
    rfKitDefault: 0, rfMileageRate: '67¢/mile', rfPerDiemDefault: 150, rfPerDiemMandatory: true,
    workingDayTypes: [], achApplicable: false, rfTaxCreditScheme: 'US_STATE',
    specialProvisions: [
      'DOT regulations apply additionally to drivers',
      'Location Managers in LA are Teamsters 399, NOT IATSE',
      'Captain/coordinator premiums apply',
      'Studio zone vehicle rules',
      '+15% night differential (highest of US unions)',
    ],
  },

  // ═══════════════════════════════════════════════════════════════════
  // CANADA
  // ═══════════════════════════════════════════════════════════════════
  {
    territoryCode: 'CA', unionKey: 'BCCFU', badge: 'BCCFU (BC)',
    effectiveFrom: new Date('2025-04-01'),
    basicHrs: 8, basicDescription: '8 hrs', hrBasis: 'Hourly rate',
    ot1Multiplier: 1.5, ot1Trigger: 'Hours 9-10', ot1Description: '×1.5',
    ot2Multiplier: 2.0, ot2Trigger: 'Hours 11+', ot2Description: '×2.0',
    goldenTimeMultiplier: null, goldenTimeAfterHours: null, goldenTimeDescription: null,
    otRateCap: null, otRateCapDescription: null,
    sixthDayMultiplier: 1.5, sixthDayDescription: '×1.5 throughout (8hr min call)',
    seventhDayMultiplier: 2.0, seventhDayDescription: '×2.0 throughout (8hr min call)',
    holidayPayPct: null, holidayPayDescription: null, hpMode: 'na',
    vacationPct: 0.04, vacationDescription: '4% vacation pay (ESA minimum)',
    nightPremiumType: null, nightPremiumValue: null, nightStartTime: null, nightEndTime: null,
    nightDescription: null,
    mealIntervalHrs: 5, mealDurationMins: 30, mealPaidStatus: 'unpaid',
    mealSubsequentInterval: 5, mealGraceMinutes: 0,
    mealPenaltyAmounts: [50], mealPenaltyDescription: 'OT rate per half-hour',
    frenchHoursAllowed: false,
    turnaroundMinHrs: 10, turnaroundDescription: '10 hrs (BC Employment Standards)',
    turnaroundPenaltyType: 'hourly_rate',
    turnaroundPenaltyDescription: 'Continuous day provisions',
    weeklyRestMinHrs: 24, dayBreakDescription: 'BC ESA',
    rfHolidayPayPct: null,
    rfNicPct: 0.0595, rfNicThreshold: null, rfNicDescription: '5.95% CPP + EI',
    rfPensionPct: 0.05, rfPensionDescription: 'H&W + RRSP + Training Fund',
    rfHwPerHour: null, rfHwDescription: 'Included in fringe package',
    rfEmployerTotalEstimate: '~30%', rfWorkersCompPct: 0.02,
    rfKitDefault: 50, rfMileageRate: '70¢/km', rfPerDiemDefault: 100, rfPerDiemMandatory: false,
    workingDayTypes: [], achApplicable: false, rfTaxCreditScheme: 'BC_VRDTC',
    specialProvisions: [
      '5.5% wage increase from April 2025 (multiply 2024-25 rates by 1.055)',
      '2% union dues deducted by production (each of IATSE 891, Teamsters 155, ICG 669)',
      'BCCFU is a coalition of IATSE 891 + Teamsters 155 + ICG 669',
    ],
  },

  // ═══════════════════════════════════════════════════════════════════
  // AUSTRALIA
  // ═══════════════════════════════════════════════════════════════════
  {
    territoryCode: 'AU', unionKey: 'AU-MEAA', badge: 'MEAA/SPA',
    effectiveFrom: new Date('2024-01-01'),
    basicHrs: 10, basicDescription: '10 hrs (standard 50hr week)', hrBasis: 'Weekly ÷ 5 ÷ 10',
    ot1Multiplier: 1.5, ot1Trigger: 'After 10hrs', ot1Description: '×1.5',
    ot2Multiplier: 2.0, ot2Trigger: 'After 12hrs', ot2Description: '×2.0',
    goldenTimeMultiplier: null, goldenTimeAfterHours: null, goldenTimeDescription: null,
    otRateCap: null, otRateCapDescription: null,
    sixthDayMultiplier: 1.5, sixthDayDescription: '×1.5',
    seventhDayMultiplier: 2.0, seventhDayDescription: '×2.0',
    holidayPayPct: null, holidayPayDescription: null, hpMode: 'na',
    vacationPct: null, vacationDescription: null,
    nightPremiumType: null, nightPremiumValue: null, nightStartTime: null, nightEndTime: null,
    nightDescription: null,
    mealIntervalHrs: 5, mealDurationMins: 30, mealPaidStatus: 'unpaid',
    mealSubsequentInterval: 5, mealGraceMinutes: 0,
    mealPenaltyAmounts: [50], mealPenaltyDescription: 'Penalty rates',
    frenchHoursAllowed: false,
    turnaroundMinHrs: 10, turnaroundDescription: '10 hrs (BRECA Award)',
    turnaroundPenaltyType: 'hourly_rate', turnaroundPenaltyDescription: 'Penalty rates',
    weeklyRestMinHrs: 24, dayBreakDescription: 'Fair Work Act',
    rfHolidayPayPct: null,
    rfNicPct: 0, rfNicThreshold: null, rfNicDescription: 'No employer NIC equivalent',
    rfPensionPct: 0.115, rfPensionDescription: 'Superannuation 11.5% MANDATORY on ALL gross (rising to 12% July 2026)',
    rfHwPerHour: null, rfHwDescription: null,
    rfEmployerTotalEstimate: '~15%', rfWorkersCompPct: 0.02,
    rfKitDefault: 0, rfMileageRate: 'A$0.88/km', rfPerDiemDefault: 0, rfPerDiemMandatory: false,
    workingDayTypes: [], achApplicable: false, rfTaxCreditScheme: 'AU_LOCATION_OFFSET',
    specialProvisions: [
      'Superannuation deadline: quarterly contributions due; late payment attracts SGC penalties',
      'Super guarantee rate: 11.5% (FY 2024-25), rising to 12% from 1 July 2026',
    ],
  },

  // ═══════════════════════════════════════════════════════════════════
  // GERMANY
  // ═══════════════════════════════════════════════════════════════════
  {
    territoryCode: 'DE', unionKey: 'DE-VERDI', badge: 'Ver.di/BFFS',
    effectiveFrom: new Date('2025-01-01'),
    basicHrs: 10, basicDescription: '10 hrs', hrBasis: 'Daily ÷ 10',
    ot1Multiplier: 1.25, ot1Trigger: 'Hour 11', ot1Description: '+25%',
    ot2Multiplier: 1.5, ot2Trigger: 'Hour 12', ot2Description: '+50% + additional hourly (non-offsettable)',
    goldenTimeMultiplier: null, goldenTimeAfterHours: null,
    goldenTimeDescription: '12-HOUR ABSOLUTE MAXIMUM — criminal liability for 13th hour',
    otRateCap: null, otRateCapDescription: null,
    sixthDayMultiplier: 1.25, sixthDayDescription: '+25% (from Sep 2025)',
    seventhDayMultiplier: 1.75, seventhDayDescription: 'Sunday: +75%',
    holidayPayPct: null, holidayPayDescription: null, hpMode: 'na',
    vacationPct: null, vacationDescription: null,
    nightPremiumType: 'percentage', nightPremiumValue: 25, nightStartTime: '22:00', nightEndTime: '06:00',
    nightDescription: '+25% for night work (22:00-06:00)',
    mealIntervalHrs: 6, mealDurationMins: 30, mealPaidStatus: 'unpaid',
    mealSubsequentInterval: 6, mealGraceMinutes: 0,
    mealPenaltyAmounts: [50], mealPenaltyDescription: 'Penalty for >10hr shooting day: mandatory second warm meal',
    frenchHoursAllowed: false,
    turnaroundMinHrs: 11, turnaroundDescription: '11 hrs MANDATORY (criminal liability)',
    turnaroundPenaltyType: null, turnaroundPenaltyDescription: 'Criminal liability — cannot violate',
    weeklyRestMinHrs: 24, dayBreakDescription: 'ArbZG requires 11hr daily rest',
    rfHolidayPayPct: null,
    rfNicPct: 0.21, rfNicThreshold: null, rfNicDescription: '~21% employer social contributions',
    rfPensionPct: 0.04, rfPensionDescription: '4% mandatory employer pension (from Jan 2025)',
    rfHwPerHour: null, rfHwDescription: null,
    rfEmployerTotalEstimate: '~30%', rfWorkersCompPct: null,
    rfKitDefault: 0, rfMileageRate: '€0.30/km', rfPerDiemDefault: 0, rfPerDiemMandatory: false,
    workingDayTypes: [], achApplicable: false, rfTaxCreditScheme: 'DE_DFFF',
    specialProvisions: [
      '12-hour ABSOLUTE MAXIMUM per day — criminal liability for employers who violate',
      'KSK (Künstlersozialkasse): ~5% on all fees to self-employed creatives',
      'Extras accounting fee: 8% on extras fees must be budgeted',
      '+2.5% crew increase from May 2025',
    ],
  },

  // ═══════════════════════════════════════════════════════════════════
  // FRANCE
  // ═══════════════════════════════════════════════════════════════════
  {
    territoryCode: 'FR', unionKey: 'FR-CCNPC', badge: 'CGT/CFDT Cinema',
    effectiveFrom: new Date('2025-07-01'),
    basicHrs: 8, basicDescription: '8 hrs (39hr standard week = 35+4)', hrBasis: 'Socle × coefficient',
    ot1Multiplier: 1.25, ot1Trigger: 'Hours 36-43', ot1Description: '+25% on base',
    ot2Multiplier: 1.5, ot2Trigger: 'Hours 44+', ot2Description: '+50% on base',
    goldenTimeMultiplier: null, goldenTimeAfterHours: null, goldenTimeDescription: null,
    otRateCap: null, otRateCapDescription: null,
    sixthDayMultiplier: 1.5, sixthDayDescription: '×1.5',
    seventhDayMultiplier: 2.0, seventhDayDescription: '×2.0 (Sunday/holiday)',
    holidayPayPct: 0.10, holidayPayDescription: '10% congés payés on gross', hpMode: 'excl',
    vacationPct: null, vacationDescription: null,
    nightPremiumType: 'percentage', nightPremiumValue: 25, nightStartTime: '22:00', nightEndTime: '06:00',
    nightDescription: '+25% for night work',
    mealIntervalHrs: 6, mealDurationMins: 60, mealPaidStatus: 'unpaid',
    mealSubsequentInterval: 6, mealGraceMinutes: 0,
    mealPenaltyAmounts: [19], mealPenaltyDescription: '€18.56 meal allowance (repas)',
    frenchHoursAllowed: false,
    turnaroundMinHrs: 11, turnaroundDescription: '11 hrs (Labour Code)',
    turnaroundPenaltyType: 'flat_penalty', turnaroundPenaltyDescription: 'Labour Code violation',
    weeklyRestMinHrs: 35, dayBreakDescription: 'French Labour Code Art. L3132-2',
    rfHolidayPayPct: 0.10, rfHolidayPayDescription: '10% congés payés',
    rfNicPct: 0.45, rfNicThreshold: null, rfNicDescription: '~45% total employer charges (ASSEDIC, URSSAF, etc.)',
    rfPensionPct: 0, rfPensionDescription: 'Included in employer charges',
    rfHwPerHour: null, rfHwDescription: null,
    rfEmployerTotalEstimate: '~55-60%', rfWorkersCompPct: null,
    rfKitDefault: 0, rfMileageRate: '€0.60/km', rfPerDiemDefault: 0, rfPerDiemMandatory: false,
    workingDayTypes: [], achApplicable: false, rfTaxCreditScheme: 'FR_C2I',
    specialProvisions: [
      'Salary grille uses socle (base value) of €821.51 — technician minimums are multiples',
      'July 2025 increases: +2.2% on salaries ≤€1,100/week; +1% on >€1,100/week',
      'Intermittent du spectacle status for freelance crew (ASSEDIC eligible)',
      'Meal allowance (repas): €18.56 per meal; casse-croûte: €7.54',
    ],
  },
];
